spring:
  application:
    name: gym-application
  datasource:
    url: jdbc:postgresql://localhost:5432/gym_application
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/liquibase-changelog.yml
    enabled: true

server:
  port: 8080
  servlet:
    context-path: /api

gym-application:
  jwt:
    secret: asdfghjklqweqygugueywqguyewqgyuegwyqgyue78187e2871ehgqeuqweygqwye